Removing unnecessary writing of images to the filesystem (#38)
* Removing old pir_pin option

* Removing unecessary writing of images to the filesystem

Also updating todo

* Fix for AttributeError: '_io.BytesIO' object has no attribute 'name'

* Fix: TypeError: bad argument type for built-in operation

* small changes in config and logging message